Added Internationalization
leoafarias/sidekick pull request #95
Opened 2021-06-17 10:37 UTC by MaximilianFlechtner

https://github.com/leoafarias/sidekick/issues/81#issue-896701712

Added Internationalization and first Language

2021-06-17 13:44 UTC, leoafarias requested changes
@MaximilianFlechtner Thank you so much for this! This is awesome. I made a few comments, but too summarize, there are string that were broken down into separate lines for readibility in the code. However they can be consolidated in the same string, instead of having multiple ones.

I think this will make things cleaner.

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/settings/scenes/fvm_settings.scene.dart
> -            subtitle: const Text('This will only clone Flutter and not install'
The subtitle is just one string, it was added the comma for legibility in the code but can be put together in the same string value for translation

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/settings/scenes/flutter_settings.scene.dart
> +                S.of(context).whenAFlutterCommandCrashesItAttempts +
All these 3 lines can be added to the same string as the space was just for readibility in the code

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/settings/scenes/flutter_settings.scene.dart
> +                        child: Text(
Can put put together in the same string also, no need to break it apart

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/releases/releases.screen.dart
> +                            S.of(context).theCurrentTipoftreeAbsoluteLatestCuttingEdgeBuild +
Can be only one string

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/projects/components/projects_empty.dart
> -              'Add your Flutter project '
One one string here also

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/packages/components/packages_empty.dart
> +              S.of(context).youNeedToAddAFlutterProjectFirst +
One string only here also

2021-06-17 13:44 UTC, leoafarias commented on lib/src/modules/common/constants.dart
> +      S.current.weRecommendThatYouUseThisChannelForAllProduction,
Can you just change these names to stableChannelDescription, where stable is the channle name, this will be a bit shorter and cleaner

2021-06-17 13:44 UTC, leoafarias commented on lib/src/components/molecules/info_banner.dart
> +                  S.of(context).theCurrentTipoftreeAbsoluteLatestCuttingEdgeBuild +
Can be only one string also

2021-06-17 18:30 UTC, MaximilianFlechtner commented
All right, I will look at the things soon and fix them. We should think about a platform for translation so that everyone can help to add their language. 

I hope I can help with more things in the future.

2021-06-18 13:44 UTC, leoafarias approved these changes

2021-06-18 13:44 UTC, merged

2021-06-18 13:45 UTC, aguilaair commented
I'll create some docs next weak and work on Spanish translation

2021-06-18 13:45 UTC, leoafarias commented
@all-contributors add @MaximilianFlechtner for code, a11y

2021-06-18 13:46 UTC, leoafarias commented
@aguilaair That would be great to have a guide on how people can collaborate.